import { gql, useLazyQuery, useQuery } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useCartToken } from "../src/useCartToken";

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <CartButton />
          </li>
        </ul>
      </nav>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const GET_CART_DETAILS = gql`
  query GetCartDetails($cartId: String!) {
    cart(cart_id: $cartId) {
      items {
        product {
          name
        }
        quantity
      }
    }
  }
`;

function CartButton() {
  const [getCartDetails, { loading, error, data }] =
    useLazyQuery(GET_CART_DETAILS);
  const getCartToken = useCartToken();

  const handleClick = async () => {
    const cartId = await getCartToken();
    getCartDetails({
      variables: {
        cartId,
      },
    });
  };

  if (loading) return <span>loading..</span>;

  // console.log(error);

  return (
    <>
      <button onClick={() => handleClick()}>Cart</button>
      <span>{data && JSON.stringify(data.cart.items)}</span>
    </>
  );
}
